uncaught exception: error(type_error(callable,1),call/1)
